platform :ios, '9.0'

target 'ReStart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReStart

    pod 'SwiftyJSON'
    pod 'Alamofire'


  target 'ReStartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReStartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
